"Ядерная оценка плонтности"
data01 <- read.delim2("Desktop/data01.txt")
hist(data01)
kde0 <- density(data01$sub1, bw = 0.5, kernel="gaussian")
kde1 <- density(data01$sub1, bw = 0.1, kernel="gaussian")
kde2 <- density(data01$sub1, bw = 0.05, kernel="gaussian")
kde3 <- density(data01$sub1, bw = 0.02, kernel="gaussian")
plot(kde0, col = "blue", ylim = c(0,10))
lines(kde1, col = "red")
lines(kde2, col = "green")
lines(kde3, col = "black")


x=rnorm(200, 10, 5)
y=x^2 + rnorm(200, 0, 5)
plot(x,y)
kr <- ksmooth(x, y, kernel = "normal", bandwidth = 0.1)
kr1 <- ksmooth(x, y, kernel = "normal", bandwidth = 10)
kr2 <- ksmooth(x, y, kernel = "normal", bandwidth = 1000)
kr3 <- ksmooth(x, y, kernel = "normal", bandwidth = 0.001)
kr4 <- ksmooth(x, y, kernel = "normal", bandwidth = 1)
kr5 <- ksmooth(x, y, kernel = "normal", bandwidth = 2.5)
lines(kr, col = 'red')
lines(kr1, col = 'blue')
lines(kr2, col = 'green')
lines(kr3, col = 'pink')
lines(kr4, col = 'gray')
lines(kr5, col = 'pink')
